services:
  postgis:
    # PostGIS 3.4.1 - Released in late 2023
    # Using this specific version for demo compatibility
    image: postgis/postgis:16-3.4.1
    platform: linux/amd64
    container_name: go-geo-index-postgis
    environment:
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopass
      POSTGRES_DB: geodb
    ports:
      - "5499:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geouser -d geodb"]
      interval: 10s
      timeout: 5s
      retries: 5